name: Docs
on: workflow_dispatch
# on:
#   push:
#     branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: mlugg/setup-zig@v1
        with:
            version: master
      - run: zig build-lib src/sokol/sokol.zig -femit-docs
      - name: rewrite-tar-file-only-sokol
        working-directory: docs
        run: |
          mkdir sources && tar -xf sources.tar -C sources
          cd sources && chmod -R 755 sokol && tar -cf sources.tar sokol
          mv sources/sources.tar . && rm -rf sources
      - name: upload-artifact
        uses: actions/upload-artifact@main
        with:
          name: sokol-zig-docs
          path: docs
          retention-days: 1
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          repository: floooh/sokol-zig-docs
          ssh-key: ${{secrets.SOKOL_ZIG_DOCS_DEPLOY}}
      - uses: actions/download-artifact@main
        with:
          name: sokol-zig-docs
      - name: "commit and push"
        run: |
          git config user.email "none"
          git config user.name "GH Action"
          git add .
          git commit -m "updated (${{ github.run_number }})"
          git push
