name: Update Docs
on: workflow_dispatch
# on:
#   push:
#     branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: mlugg/setup-zig@v1
        with:
            version: master
      - run: zig build-lib src/sokol/sokol.zig -femit-docs
      - name: Update pages artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          repository: floooh/sokol-zig-docs
          ssh-key: ${{secrets.SOKOL_ZIG_DOCS_DEPLOY}}
      - uses: actions/download-artifact@main
        with:
          name: sokol-zig-docs
      - name: "commit and push"
        run: |
          git config user.email "none"
          git config user.name "GH Action"
          git add .
          git commit -m "updated (${{ github.run_number }})"
          git push
