name: Zig

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        # FIXME: temporarily remove windows build because of build errors
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@main
      - uses: mlugg/setup-zig@v1
        with:
            version: master
      - name: prepare-linux
        if: runner.os == 'Linux'
        run: |
            sudo apt-get update
            sudo apt-get install libglu1-mesa-dev mesa-common-dev xorg-dev libasound-dev
      - name: build Native
        run: zig build --summary all
      - name: build Wasm
        run: zig build --summary all -Dtarget=wasm32-emscripten
